### ISSUE TITLE
failed to start minecraft server error

### ISSUE THREAD

**Issue by axotailyn** [rvbsm/fsit#38]
### 🔍 What happened?

get an error after trying to start my server with fsit installed, apparently it is clashing with the mod "create track map"

### 🤔 What did you expect to happen?

the server to start normally

### 📦 Version

2.3.1

### ⛏ Minecraft Version

1.20.1 Fabric

### 📃 Relevant log output

```bash
[23:16:15] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fsit'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.10.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.1]
Caused by: java.lang.NoSuchMethodError: 'void kotlinx.serialization.json.JsonBuilder.setNamingStrategy(kotlinx.serialization.json.JsonNamingStrategy)'
        at dev.rvbsm.fsit.config.ModConfigKt$json$1.invoke(ModConfig.kt:25) ~[fsit-2.3.1+1.20.1.jar:?]
        at dev.rvbsm.fsit.config.ModConfigKt$json$1.invoke(ModConfig.kt:25) ~[fsit-2.3.1+1.20.1.jar:?]
        at kotlinx.serialization.json.JsonKt.Json(Json.kt:187) ~[create-track-map-1.4+mc1.20.1-fabric.jar:?]
        at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:185) ~[create-track-map-1.4+mc1.20.1-fabric.jar:?]
        at dev.rvbsm.fsit.config.ModConfigKt.<clinit>(ModConfig.kt:25) ~[fsit-2.3.1+1.20.1.jar:?]
        at dev.rvbsm.fsit.config.ModConfig$Companion.read$fsit(ModConfig.kt:61) ~[fsit-2.3.1+1.20.1.jar:?]
        at dev.rvbsm.fsit.FSitMod.loadConfig(FSitMod.kt:47) ~[fsit-2.3.1+1.20.1.jar:?]
        at dev.rvbsm.fsit.FSitMod.onInitialize(FSitMod.kt:24) ~[fsit-2.3.1+1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
        ... 7 more
```

**Comment by rvbsm** [comment]
> it is clashing with the mod "create track map"

Yep, Create Track Map shadows (includes) old version of Fabric Language Kotlin. jenchanws/create-track-map#61.

[There is a fork](https://github.com/solonovamax/create-track-map), that fixes this issue, but it seems like the mod is no longer maintained and the fix will not be merged any time soon.
You can either build it by yourself or just use my build: 
[create-track-map-1.4+mc1.20.1-fabric.zip](https://github.com/rvbsm/fsit/files/15452430/create-track-map-1.4%2Bmc1.20.1-fabric.zip)
