### ISSUE TITLE
bug: Crash on latest release

### ISSUE THREAD

**Issue by sternschnaube** [rvbsm/fsit#39]
### 🔍 What happened?

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fsit'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'UUID' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.SerializersKt__SerializersKt.noCompiledSerializer(Serializers.kt:366)
	at kotlinx.serialization.SerializersKt.noCompiledSerializer(Unknown Source)
	at dev.rvbsm.fsit.client.config.RestrictionList.load(RestrictionList.kt:48)
	at dev.rvbsm.fsit.client.FSitModClient.onInitializeClient(FSitModClient.kt:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

### 🤔 What did you expect to happen?

/

### 📦 Version

v2.3.2

### ⛏ Minecraft Version

1.20.6

**Comment by rvbsm** [comment]
Released [v2.3.3](https://modrinth.com/mod/fsit/version/2.3.3+1.20.6)

**Comment by venaminecraft** [comment]
Thanks 😊

**Comment by slushieuwu** [comment]
i still get this issue, its caused by 'fsit.restrictions.json' not existing in the config folder :3

**Comment by slushieuwu** [comment]
quite silly that a file with only 2 square brackets is enough to make the game stop from launching :p

**Comment by slushieuwu** [comment]
video:
https://github.com/rvbsm/fsit/assets/86991346/fbdbbde7-23ed-400a-96a2-2372a6d7c4de
all the file is :p
[fsit.restrictions.json](https://github.com/rvbsm/fsit/files/15479302/fsit.restrictions.json)

**Comment by slushieuwu** [comment]
almost forgot the crashlog:
https://mclo.gs/ARK80HE

**Comment by rvbsm** [comment]
Huh uh. Trying to revert Kotlin version then

**Comment by rvbsm** [comment]
Seems like it worked… Kotlin 2.0 release is kinda cursed

**Comment by rvbsm** [comment]
Fixed (maybe) in [v2.3.4](https://modrinth.com/mod/fsit/version/2.3.4+1.20.6)

Thanks for reporting the issue!
