### ISSUE TITLE
bug: Mod isn't creating a config on start

### ISSUE THREAD

**Issue by Im-0xC7** [rvbsm/fsit#48]
### 🔍 What happened?

The mod isn't creating the default config on startup and throws a (non-fatal) NoSuchFileException

### 🤔 What did you expect to happen?

For the mod to create a default config file

### 📦 Version

Tested with 2.7.0 & 2.7.1

### ⛏ Minecraft Version

Tested on 1.21.3 & 1.21.4

### 📃 Relevant log output

```bash
1.21.3 & v2.7.1
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[22:22:18] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.9
[22:22:18] [main/INFO]: Loading 56 mods:
        - fabric-api 0.110.0+1.21.3
           |-- fabric-api-base 0.4.50+119c825640
           |-- fabric-api-lookup-api-v1 1.6.81+fd37071f40
           |-- fabric-biome-api-v1 14.0.6+fd37071f40
           |-- fabric-block-api-v1 1.0.28+fd37071f40
           |-- fabric-block-view-api-v2 1.0.16+fd37071f40
           |-- fabric-blockrenderlayer-v1 2.0.4+fd37071f40
           |-- fabric-client-tags-api-v1 1.1.24+fd37071f40
           |-- fabric-command-api-v1 1.2.58+f71b366f40
           |-- fabric-command-api-v2 2.2.37+c9d82ab240
           |-- fabric-commands-v0 0.2.75+df3654b340
           |-- fabric-content-registries-v0 9.1.8+fd37071f40
           |-- fabric-convention-tags-v1 2.1.3+7f945d5b40
           |-- fabric-convention-tags-v2 2.9.3+84ebbb0e40
           |-- fabric-crash-report-info-v1 0.3.3+fd37071f40
           |-- fabric-data-attachment-api-v1 1.4.0+dbad41f140
           |-- fabric-data-generation-api-v1 21.0.18+fd37071f40
           |-- fabric-dimensions-v1 4.0.7+fd37071f40
           |-- fabric-entity-events-v1 2.0.8+825023f840
           |-- fabric-events-interaction-v0 2.0.12+c2c3ac4740
           |-- fabric-game-rule-api-v1 1.0.59+fd37071f40
           |-- fabric-item-api-v1 11.1.7+fd37071f40
           |-- fabric-item-group-api-v1 4.1.17+fd37071f40
           |-- fabric-key-binding-api-v1 1.0.53+fd37071f40
           |-- fabric-keybindings-v0 0.2.51+df3654b340
           |-- fabric-lifecycle-events-v1 2.5.1+6da5ef6940
           |-- fabric-loot-api-v2 3.0.26+3f89f5a540
           |-- fabric-loot-api-v3 1.0.14+fd37071f40
           |-- fabric-message-api-v1 6.0.21+fd37071f40
           |-- fabric-model-loading-api-v1 3.0.9+fd37071f40
           |-- fabric-networking-api-v1 4.3.5+fd37071f40
           |-- fabric-object-builder-api-v1 17.0.9+fd37071f40
           |-- fabric-particles-v1 4.0.10+fd37071f40
           |-- fabric-recipe-api-v1 7.0.4+fd37071f40
           |-- fabric-registry-sync-v0 5.3.0+2758bfbf40
           |-- fabric-renderer-api-v1 4.0.5+fd37071f40
           |-- fabric-renderer-indigo 1.9.5+fd37071f40
           |-- fabric-rendering-data-attachment-v1 0.3.54+73761d2e40
           |-- fabric-rendering-fluids-v1 3.1.15+fd37071f40
           |-- fabric-rendering-v0 1.1.84+df3654b340
           |-- fabric-rendering-v1 8.0.8+6922831640
           |-- fabric-resource-conditions-api-v1 5.0.8+fd37071f40
           |-- fabric-resource-loader-v0 3.0.6+fd37071f40
           |-- fabric-screen-api-v1 2.0.34+fd37071f40
           |-- fabric-screen-handler-api-v1 1.3.101+fd37071f40
           |-- fabric-sound-api-v1 1.0.29+fd37071f40
           |-- fabric-transfer-api-v1 5.4.3+fd37071f40
           \-- fabric-transitive-access-wideners-v1 6.2.0+54a41b1c40
        - fabric-language-kotlin 1.13.0+kotlin.2.1.0
           |-- org_jetbrains_kotlin_kotlin-reflect 2.1.0
           |-- org_jetbrains_kotlin_kotlin-stdlib 2.1.0
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.1.0
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.1.0
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.26.1
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
           |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.6.0
           |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.6.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
        - fabricloader 0.16.9
           \-- mixinextras 0.4.1
        - fsit 2.7.1+mc1.21.2
        - java 21
        - minecraft 1.21.3
[22:22:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/[...]/Documents/TestFabricServer/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[22:22:19] [main/INFO]: Compatibility level set to JAVA_21
[22:22:19] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[22:22:24] [DefaultDispatcher-worker-1/ERROR]: Failed to read from .\config\fsit.yml
java.nio.file.NoSuchFileException: .\config\fsit.yml
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234) ~[?:?]
        at java.base/java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?]
        at java.base/java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?]
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
        at java.base/java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
        at knot/kotlin.io.path.PathsKt__PathReadWriteKt.readText(PathReadWrite.kt:157) ~[org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
        at knot/kotlin.io.path.PathsKt__PathReadWriteKt.readText$default(PathReadWrite.kt:153) ~[org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
        at knot/dev.rvbsm.fsit.serialization.StringDataReader.read(DataReader.kt:60) ~[fsit-2.7.1+mc1.21.2.jar:?]
        at knot/dev.rvbsm.fsit.serialization.StringDataReader.read(DataReader.kt:53) ~[fsit-2.7.1+mc1.21.2.jar:?]
        at knot/dev.rvbsm.fsit.serialization.DataReader$read$2.invokeSuspend(DataReader.kt:42) [fsit-2.7.1+mc1.21.2.jar:?]
        at knot/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
        at knot/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
[22:22:24] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:22:25] [main/INFO]: No existing world data, creating new world
[22:22:26] [main/INFO]: Loaded 1337 recipes
[22:22:26] [main/INFO]: Loaded 1448 advancements
[22:22:26] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.336 ms
[22:22:26] [Server thread/INFO]: Starting minecraft server version 1.21.3
[22:22:26] [Server thread/INFO]: Loading properties
[22:22:26] [Server thread/INFO]: Default game type: SURVIVAL
[22:22:26] [Server thread/INFO]: Generating keypair
[22:22:26] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:22:26] [Server thread/INFO]: Using default channel type
[22:22:26] [Server thread/INFO]: Preparing level "world"
[22:22:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:22:28] [Worker-Main-15/INFO]: Preparing spawn area: 2%
[22:22:29] [Worker-Main-5/INFO]: Preparing spawn area: 2%
[22:22:29] [Worker-Main-4/INFO]: Preparing spawn area: 18%
[22:22:30] [Worker-Main-15/INFO]: Preparing spawn area: 51%
[22:22:30] [Server thread/INFO]: Time elapsed: 1713 ms
[22:22:30] [Server thread/INFO]: Done (3.787s)! For help, type "help"



Snippet from one of my servers on 1.21.4 and with v2.7.0
[21:54:52] [DefaultDispatcher-worker-1/ERROR]: Failed to read from ./config/fsit.yml
java.nio.file.NoSuchFileException: ./config/fsit.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.base/java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
	at knot/kotlin.io.path.PathsKt__PathReadWriteKt.readText(PathReadWrite.kt:157) ~[org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
	at knot/kotlin.io.path.PathsKt__PathReadWriteKt.readText$default(PathReadWrite.kt:153) ~[org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
	at knot/dev.rvbsm.fsit.serialization.StringDataReader.read(DataReader.kt:60) ~[fsit-2.7.0+mc1.21.2.jar:?]
	at knot/dev.rvbsm.fsit.serialization.StringDataReader.read(DataReader.kt:53) ~[fsit-2.7.0+mc1.21.2.jar:?]
	at knot/dev.rvbsm.fsit.serialization.DataReader$read$2.invokeSuspend(DataReader.kt:42) [fsit-2.7.0+mc1.21.2.jar:?]
	at knot/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
	at knot/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at knot/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
```

**Comment by rvbsm** [comment]
Thank you, totally forgot about it. Fixed in [v2.7.2](https://modrinth.com/mod/fsit/version/2.7.2+mc1.21.2)
